### ISSUE TITLE
Collation Mismatch

### ISSUE THREAD

**Issue by z0lo13** [WalkingPizza/strapi-plugin-placeholder#7]
migration 2022.08.26T00.00.00.generate-placeholders-for-existing-images.js (up) failed: Original error: select `id`, `url` from `files` where `url` is not null and `mime` like 'image/%' COLLATE utf8_bin and `placeholder` is null and `id` > 0 order by `id` asc limit 1000 - ER_COLLATION_CHARSET_MISMATCH: COLLATION 'utf8mb3_bin' is not valid for CHARACTER SET 'utf8mb4'
MigrationError: Migration 2022.08.26T00.00.00.generate-placeholders-for-existing-images.js (up) failed: Original error: select `id`, `url` from `files` where `url` is not null and `mime` like 'image/%' COLLATE utf8_bin and `placeholder` is null and `id` > 0 order by `id` asc limit 1000 - ER_COLLATION_CHARSET_MISMATCH: COLLATION 'utf8mb3_bin' is not valid for CHARACTER SET 'utf8mb4'
    at /home/apps/hmcMainApi/node_modules/umzug/lib/umzug.js:151:27
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Umzug.runCommand (/home/apps/hmcMainApi/node_modules/umzug/lib/umzug.js:107:20)
    at async Object.up (/home/apps/hmcMainApi/node_modules/@strapi/database/lib/migrations/index.js:67:7)
    at async Object.sync (/home/apps/hmcMainApi/node_modules/@strapi/database/lib/schema/index.js:68:9)
    at async Strapi.bootstrap (/home/apps/hmcMainApi/node_modules/@strapi/strapi/lib/Strapi.js:429:5)
    at async Strapi.load (/home/apps/hmcMainApi/node_modules/@strapi/strapi/lib/Strapi.js:457:5)
    at async Strapi.start (/home/apps/hmcMainApi/node_modules/@strapi/strapi/lib/Strapi.js:198:9)

**Comment by WalkingPizza** [comment]
This is a MySQL issue which I don't believe can be solved in the migration script.
Try changing the charset/collation settings in your database so that the two values are compatible.
